spring:
  application:
    name: core-service

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: micro, logging, corestore

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: micromarket


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /EN/v3/api-docs
        name: English Greetings Service
      - url: /GE/v3/api-docs
        name: German Greetings Service